name: Autoincrement the Git tag and publish a Debian package

on:
  push:
    branches: [ 'master' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


### auto update the Git tag
### build the Debian package
### release the package
### https://github.com/marketplace/actions/create-release

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - uses: actions/checkout@v2
      - run: sh build-deb.sh ${{ steps.bump-semver.outputs.new_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: socksd
          path: deb/socksd_${{ steps.bump-semver.outputs.new_version }}.deb

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "deb/socksd_${{ steps.bump-semver.outputs.new_version }}.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
